[package]
name = "rust-graphql-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
poem = "1.0"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
